# ==============================================================================
# constants.py - COFRE DE CONSTANTES DA INTERFACE E FILTROS
# ==============================================================================
# ATENÇÃO IA: É ESTRITAMENTE PROIBIDO alterar, traduzir, resumir ou modificar
# a estrutura, as chaves ou os valores (exceto a restauração posterior pelo
# usuário) dos dicionários deste arquivo no futuro.
# ==============================================================================

UI_MAPPING = {
    "Create New Mesh": [
        "create_cube",
        "create_sphere",
        "create_sphere_cap",
        "create_torus",
        "create_annulus",
        "create_cone",
        "create_dodecahedron",
        "create_dodecahedron_sym",
        "create_icosahedron",
        "create_octahedron",
        "create_tetrahedron",
        "create_grid",
        "create_noisy_isosurface",
        "generate_plane_fitting_to_selection",
        "create_fractal_terrain",
        "create_implicit_surface",
    ],
    "Remeshing, Simplification and Reconstruction": [
        "meshing_isotropic_explicit_remeshing",
        "generate_resampled_uniform_mesh",
        "generate_convex_hull",
        "meshing_surface_subdivision_butterfly",
        "meshing_surface_subdivision_catmull_clark",
        "meshing_surface_subdivision_doo_sabin",
        "meshing_surface_subdivision_ls3_loop",
        "meshing_surface_subdivision_loop",
        "meshing_surface_subdivision_midpoint",
        "meshing_decimation_clustering",
        "meshing_decimation_edge_collapse_for_marching_cube_meshes",
        "meshing_decimation_quadric_edge_collapse",
        "meshing_decimation_quadric_edge_collapse_with_texture",
    ],
}

FILTER_NAMES = {
    "create_cube": "Box/Cube",
    "create_sphere": "Sphere",
    "create_sphere_cap": "Sphere Cap",
    "create_torus": "Torus",
    "create_annulus": "Annulus",
    "create_cone": "Cone",
    "create_dodecahedron": "Dodecahedron",
    "create_dodecahedron_sym": "Dodecahedron (symmetric)",
    "create_icosahedron": "Icosahedron",
    "create_octahedron": "Octahedron",
    "create_tetrahedron": "Tetrahedron",
    "create_grid": "Grid Generator",
    "create_noisy_isosurface": "Noisy Isosurface",
    "generate_plane_fitting_to_selection": "Fit a plane to selection",
    "create_fractal_terrain": "Fractal Terrain",
    "meshing_isotropic_explicit_remeshing": "Remeshing: Isotropic Explicit Remeshing",
    "generate_resampled_uniform_mesh": "Uniform Mesh Resampling",
    "generate_convex_hull": "Convex Hull",
    "create_implicit_surface": "Implicit Surface",
    "meshing_surface_subdivision_butterfly": "Subdivision Surfaces: Butterfly",
    "meshing_surface_subdivision_catmull_clark": "Subdivision Surfaces: Catmull-Clark",
    "meshing_surface_subdivision_doo_sabin": "Subdivision Surfaces: Doo-Sabin",
    "meshing_surface_subdivision_ls3_loop": "Subdivision Surfaces: LS3 Loop",
    "meshing_surface_subdivision_loop": "Subdivision Surfaces: Loop",
    "meshing_surface_subdivision_midpoint": "Subdivision Surfaces: Midpoint",
    "meshing_decimation_clustering": "Simplification: Clustering Decimation",
    "meshing_decimation_edge_collapse_for_marching_cube_meshes": "Simplification: Edge Collapse for Marching Cube Meshes",
    "meshing_decimation_quadric_edge_collapse": "Simplification: Quadric Edge Collapse Decimation",
    "meshing_decimation_quadric_edge_collapse_with_texture": "Simplification: Quadric Edge Collapse Decimation (with texture)",
}

FILTER_DESCRIPTIONS = {
    "create_cube": "TBD",
    "create_sphere": "TBD",
    "create_sphere_cap": "TBD",
    "create_torus": "TBD",
    "create_annulus": "TBD",
    "create_cone": "TBD",
    "create_dodecahedron": "TBD",
    "create_dodecahedron_sym": "TBD",
    "create_icosahedron": "TBD",
    "create_octahedron": "TBD",
    "create_tetrahedron": "TBD",
    "create_grid": "TBD",
    "create_noisy_isosurface": "TBD",
    "generate_plane_fitting_to_selection": "TBD",
    "create_fractal_terrain": "TBD",
    "meshing_isotropic_explicit_remeshing": "TBD",
    "generate_resampled_uniform_mesh": "TBD",
    "generate_convex_hull": "TBD",
    "create_implicit_surface": "TBD",
    "meshing_surface_subdivision_butterfly": "TBD",
    "meshing_surface_subdivision_catmull_clark": "TBD",
    "meshing_surface_subdivision_doo_sabin": "TBD",
    "meshing_surface_subdivision_ls3_loop": "TBD",
    "meshing_surface_subdivision_loop": "TBD",
    "meshing_surface_subdivision_midpoint": "TBD",
    "meshing_decimation_clustering": "TBD",
    "meshing_decimation_edge_collapse_for_marching_cube_meshes": "TBD",
    "meshing_decimation_quadric_edge_collapse": "TBD",
    "meshing_decimation_quadric_edge_collapse_with_texture": "TBD",
}
