# ==============================================================================
# constants.py - COFRE DE CONSTANTES DA INTERFACE E FILTROS
# ==============================================================================
# ATENÇÃO IA: É ESTRITAMENTE PROIBIDO alterar, traduzir, resumir ou modificar
# a estrutura, as chaves ou os valores (exceto a restauração posterior pelo
# usuário) dos dicionários deste arquivo no futuro.
# ==============================================================================

UI_MAPPING = {
    "Create New Mesh": [
        "create_cube",
        "create_sphere",
        "create_sphere_cap",
        "create_torus",
        "create_annulus",
        "create_cone",
        "create_dodecahedron",
        "create_dodecahedron_sym",
        "create_icosahedron",
        "create_octahedron",
        "create_tetrahedron",
        "create_grid",
        "create_noisy_isosurface",
        "generate_plane_fitting_to_selection",
        "create_fractal_terrain",
        "create_implicit_surface",
        "create_sphere_points",
    ],
    "Remeshing, Simplification and Reconstruction": [
        "meshing_isotropic_explicit_remeshing",
        "generate_resampled_uniform_mesh",
        "generate_convex_hull",
        "meshing_surface_subdivision_butterfly",
        "meshing_surface_subdivision_catmull_clark",
        "meshing_surface_subdivision_doo_sabin",
        "meshing_surface_subdivision_ls3_loop",
        "meshing_surface_subdivision_loop",
        "meshing_surface_subdivision_midpoint",
        "meshing_decimation_clustering",
        "meshing_decimation_edge_collapse_for_marching_cube_meshes",
        "meshing_decimation_quadric_edge_collapse",
        "meshing_decimation_quadric_edge_collapse_with_texture",
        "generate_surface_reconstruction_vcg",
        "generate_surface_reconstruction_screened_poisson",
        "generate_surface_reconstruction_ball_pivoting",
        "meshing_poly_to_tri",
        "meshing_tri_to_quad_by_4_8_subdivision",
        "meshing_tri_to_quad_by_smart_triangle_pairing",
        "meshing_tri_to_quad_dominant",
        "generate_boolean_difference",
        "generate_boolean_intersection",
        "generate_boolean_union",
        "generate_boolean_xor",
        "meshing_close_holes",
        "meshing_edge_flip_by_planar_optimization",
        "meshing_edge_flip_by_curvature_optimization",
        "generate_solid_wireframe",
        "apply_coord_cubic_stylization",
    ],
    "Sampling": [
        "generate_sampling_clustered_vertex",
        "generate_sampling_element",
        "generate_sampling_montecarlo",
        "generate_sampling_poisson_disk",
        "generate_sampling_regular_recursive",
        "generate_sampling_stratified_triangle",
        "generate_sampling_volumetric",
        "generate_sampling_voronoi",
        "generate_simplified_point_cloud",
    ],
    "Normals, Curvatures and Orientation": [
        "compute_normal_for_point_clouds",
        "meshing_invert_face_orientation",
        "meshing_re_orient_faces_coherently",
    ],
    "Smoothing, Fairing and Deformation": [
        "apply_coord_taubin_smoothing",
        "apply_coord_two_steps_smoothing",
        "apply_coord_depth_smoothing",
        "apply_coord_fractal_displacement",
        "apply_coord_hc_laplacian_smoothing",
        "apply_coord_laplacian_smoothing",
        "apply_coord_laplacian_smoothing_surface_preserving",
        "apply_coord_random_displacement",
        "apply_coord_laplacian_smoothing_scale_dependent",
        "apply_coord_unsharp_mask",
    ],
    "Quality Measure and Computations": [
        "meshing_re_orient_faces_by_geometry",
    ],
    "Cleaning and Repairing": [
        "meshing_remove_unreferenced_vertices",
        "meshing_remove_connected_component_by_diameter",
        "meshing_remove_connected_component_by_face_number",
        "meshing_remove_duplicate_faces",
        "meshing_remove_folded_faces",
        "meshing_remove_null_faces",
        "meshing_remove_t_vertices",
        "meshing_remove_vertices_by_scalar",
        "meshing_snap_mismatched_borders",
        "meshing_repair_non_manifold_edges",
        "meshing_repair_non_manifold_vertices",
    ],
}

FILTER_NAMES = {
    "create_cube": "Box/Cube",
    "create_sphere": "Sphere",
    "create_sphere_cap": "Sphere Cap",
    "create_torus": "Torus",
    "create_annulus": "Annulus",
    "create_cone": "Cone",
    "create_dodecahedron": "Dodecahedron",
    "create_dodecahedron_sym": "Dodecahedron (symmetric)",
    "create_icosahedron": "Icosahedron",
    "create_octahedron": "Octahedron",
    "create_tetrahedron": "Tetrahedron",
    "create_grid": "Grid Generator",
    "create_noisy_isosurface": "Noisy Isosurface",
    "generate_plane_fitting_to_selection": "Fit a plane to selection",
    "create_fractal_terrain": "Fractal Terrain",
    "meshing_isotropic_explicit_remeshing": "Remeshing: Isotropic Explicit Remeshing",
    "generate_resampled_uniform_mesh": "Uniform Mesh Resampling",
    "generate_convex_hull": "Convex Hull",
    "create_implicit_surface": "Implicit Surface",
    "meshing_surface_subdivision_butterfly": "Subdivision Surfaces: Butterfly",
    "meshing_surface_subdivision_catmull_clark": "Subdivision Surfaces: Catmull-Clark",
    "meshing_surface_subdivision_doo_sabin": "Subdivision Surfaces: Doo-Sabin",
    "meshing_surface_subdivision_ls3_loop": "Subdivision Surfaces: LS3 Loop",
    "meshing_surface_subdivision_loop": "Subdivision Surfaces: Loop",
    "meshing_surface_subdivision_midpoint": "Subdivision Surfaces: Midpoint",
    "meshing_decimation_clustering": "Simplification: Clustering Decimation",
    "meshing_decimation_edge_collapse_for_marching_cube_meshes": "Simplification: Edge Collapse for Marching Cube Meshes",
    "meshing_decimation_quadric_edge_collapse": "Simplification: Quadric Edge Collapse Decimation",
    "meshing_decimation_quadric_edge_collapse_with_texture": "Simplification: Quadric Edge Collapse Decimation (with texture)",
    "generate_surface_reconstruction_vcg": "Surface Reconstruction: VCG",
    "compute_normal_for_point_clouds": "Compute normals for point sets",
    "generate_surface_reconstruction_screened_poisson": "Surface Reconstruction: Screened Poisson",
    "generate_surface_reconstruction_ball_pivoting": "Surface Reconstruction: Ball Pivoting",
    "meshing_poly_to_tri": "Turn into a Pure-Triangular mesh",
    "meshing_tri_to_quad_by_4_8_subdivision": "Tri to Quad by 4-8 Subdivision",
    "meshing_tri_to_quad_by_smart_triangle_pairing": "Tri to Quad by smart triangle pairing",
    "meshing_tri_to_quad_dominant": "Turn into Quad-Dominant mesh",
    "generate_boolean_difference": "Mesh Boolean: Difference",
    "generate_boolean_intersection": "Mesh Boolean: Intersection",
    "generate_boolean_union": "Mesh Boolean: Union",
    "generate_boolean_xor": "Mesh Boolean: Symmetric Difference (XOR)",
    "meshing_re_orient_faces_by_geometry": "Reorient face normals by geometry",
    "meshing_invert_face_orientation": "Invert Faces Orientation",
    "meshing_re_orient_faces_coherently": "Re-Orient all faces coherently",
    "meshing_remove_unreferenced_vertices": "Remove Unreferenced Vertices",
    "meshing_remove_connected_component_by_diameter": "Remove Isolated pieces (wrt Diameter)",
    "meshing_remove_connected_component_by_face_number": "Remove Isolated pieces (wrt Face Num.)",
    "meshing_remove_duplicate_faces": "Remove Duplicate Faces",
    "meshing_remove_folded_faces": "Remove Isolated Folded Faces by Edge Flip",
    "meshing_remove_null_faces": "Remove Zero Area Faces",
    "meshing_remove_t_vertices": "Remove T-Vertices",
    "meshing_remove_vertices_by_scalar": "Remove Vertices wrt Quality",
    "meshing_snap_mismatched_borders": "Snap Mismatched Borders",
    "create_sphere_points": "Points on a Sphere",
    "meshing_repair_non_manifold_edges": "Repair non Manifold Edges",
    "meshing_repair_non_manifold_vertices": "Repair non Manifold Vertices by splitting",
    "meshing_close_holes": "Close Holes",
    "meshing_edge_flip_by_planar_optimization": "Planar flipping optimization",
    "meshing_edge_flip_by_curvature_optimization": "Curvature flipping optimization",
    "generate_sampling_clustered_vertex": "Clustered Vertex Sampling",
    "generate_sampling_element": "Mesh Element Sampling",
    "generate_sampling_montecarlo": "Montecarlo Sampling",
    "generate_sampling_poisson_disk": "Poisson-disk Sampling",
    "generate_sampling_regular_recursive": "Regular Recursive Sampling",
    "generate_sampling_stratified_triangle": "Stratified Triangle Sampling",
    "generate_sampling_volumetric": "Volumetric Sampling",
    "generate_sampling_voronoi": "Voronoi Sampling",
    "generate_simplified_point_cloud": "Point Cloud Simplification",
    "generate_solid_wireframe": "Create Solid Wireframe",
    "apply_coord_taubin_smoothing": "Taubin Smooth",
    "apply_coord_two_steps_smoothing": "TwoStep Smooth",
    "apply_coord_depth_smoothing": "Depth Smooth",
    "apply_coord_fractal_displacement": "Fractal Displacement",
    "apply_coord_hc_laplacian_smoothing": "HC Laplacian Smooth",
    "apply_coord_laplacian_smoothing": "Laplacian Smooth",
    "apply_coord_laplacian_smoothing_surface_preserving": "Laplacian Smooth (surface preserving)",
    "apply_coord_random_displacement": "Random Vertex Displacement",
    "apply_coord_laplacian_smoothing_scale_dependent": "ScaleDependent Laplacian Smooth",
    "apply_coord_unsharp_mask": "UnSharp Mask Geometry",
    "apply_coord_cubic_stylization": "Cubic stylization",
}

FILTER_DESCRIPTIONS = {
    "create_cube": "TBD",
    "create_sphere": "TBD",
    "create_sphere_cap": "TBD",
    "create_torus": "TBD",
    "create_annulus": "TBD",
    "create_cone": "TBD",
    "create_dodecahedron": "TBD",
    "create_dodecahedron_sym": "TBD",
    "create_icosahedron": "TBD",
    "create_octahedron": "TBD",
    "create_tetrahedron": "TBD",
    "create_grid": "TBD",
    "create_noisy_isosurface": "TBD",
    "generate_plane_fitting_to_selection": "TBD",
    "create_fractal_terrain": "TBD",
    "meshing_isotropic_explicit_remeshing": "TBD",
    "generate_resampled_uniform_mesh": "TBD",
    "generate_convex_hull": "TBD",
    "create_implicit_surface": "TBD",
    "meshing_surface_subdivision_butterfly": "TBD",
    "meshing_surface_subdivision_catmull_clark": "TBD",
    "meshing_surface_subdivision_doo_sabin": "TBD",
    "meshing_surface_subdivision_ls3_loop": "TBD",
    "meshing_surface_subdivision_loop": "TBD",
    "meshing_surface_subdivision_midpoint": "TBD",
    "meshing_decimation_clustering": "TBD",
    "meshing_decimation_edge_collapse_for_marching_cube_meshes": "TBD",
    "meshing_decimation_quadric_edge_collapse": "TBD",
    "meshing_decimation_quadric_edge_collapse_with_texture": "TBD",
    "generate_surface_reconstruction_vcg": "TBD",
    "compute_normal_for_point_clouds": "TBD",
    "generate_surface_reconstruction_screened_poisson": "TBD",
    "generate_surface_reconstruction_ball_pivoting": "TBD",
    "meshing_poly_to_tri": "TBD",
    "meshing_tri_to_quad_by_4_8_subdivision": "TBD",
    "meshing_tri_to_quad_by_smart_triangle_pairing": "TBD",
    "meshing_tri_to_quad_dominant": "TBD",
    "generate_boolean_difference": "TBD",
    "generate_boolean_intersection": "TBD",
    "generate_boolean_union": "TBD",
    "generate_boolean_xor": "TBD",
    "meshing_re_orient_faces_by_geometry": "TBD",
    "meshing_invert_face_orientation": "TBD",
    "meshing_re_orient_faces_coherently": "TBD",
    "meshing_remove_unreferenced_vertices": "TBD",
    "meshing_remove_connected_component_by_diameter": "TBD",
    "meshing_remove_connected_component_by_face_number": "TBD",
    "meshing_remove_duplicate_faces": "TBD",
    "meshing_remove_folded_faces": "TBD",
    "meshing_remove_null_faces": "TBD",
    "meshing_remove_t_vertices": "TBD",
    "meshing_remove_vertices_by_scalar": "TBD",
    "meshing_snap_mismatched_borders": "TBD",
    "create_sphere_points": "TBD",
    "meshing_repair_non_manifold_edges": "TBD",
    "meshing_repair_non_manifold_vertices": "TBD",
    "meshing_close_holes": "TBD",
    "meshing_edge_flip_by_planar_optimization": "TBD",
    "meshing_edge_flip_by_curvature_optimization": "TBD",
    "generate_sampling_clustered_vertex": "TBD",
    "generate_sampling_element": "TBD",
    "generate_sampling_montecarlo": "TBD",
    "generate_sampling_poisson_disk": "TBD",
    "generate_sampling_regular_recursive": "TBD",
    "generate_sampling_stratified_triangle": "TBD",
    "generate_sampling_volumetric": "TBD",
    "generate_sampling_voronoi": "TBD",
    "generate_simplified_point_cloud": "TBD",
    "generate_solid_wireframe": "TBD",
    "apply_coord_taubin_smoothing": "TBD",
    "apply_coord_two_steps_smoothing": "TBD",
    "apply_coord_depth_smoothing": "TBD",
    "apply_coord_fractal_displacement": "TBD",
    "apply_coord_hc_laplacian_smoothing": "TBD",
    "apply_coord_laplacian_smoothing": "TBD",
    "apply_coord_laplacian_smoothing_surface_preserving": "TBD",
    "apply_coord_random_displacement": "TBD",
    "apply_coord_laplacian_smoothing_scale_dependent": "TBD",
    "apply_coord_unsharp_mask": "TBD",
    "apply_coord_cubic_stylization": "TBD",
}
