import bpy
import pymeshlab
from bpy.types import PropertyGroup
from bpy.props import FloatProperty, BoolProperty, IntProperty
from ..base_filter import MeshLabFilterBase

# ==============================================================================
# Filtros relacionados a geração/reconstrução de malhas baseados na API do PyMeshLab.
# ==============================================================================


class MESHLAB_PG_generate_resampled_uniform_mesh(PropertyGroup, MeshLabFilterBase):
    pymeshlab_filter = "generate_resampled_uniform_mesh"
    requires_selection = True
    shade_flat = True
    remove_attributes = ["custom_normal", "sharp_edge", "sharp_face"]
    percentage_parameters = ["cellsize", "offset"]

    def is_property_hidden(self, key):
        # UI Dinâmica: Alterna a exibição entre o slider livre e o slider protegido
        if key == "offset" and self.absdist:
            return True
        if key == "ui_offset_abs" and not self.absdist:
            return True
        return False

    @classmethod
    def pre_process_parameters(cls, params, props):
        # Injeção de Dados: Se absoluto está ativo, pega o valor do slider seguro
        # e injeta no parâmetro 'offset' original que o PyMeshLab exige.
        if props.absdist:
            params["offset"] = pymeshlab.PureValue(float(props.ui_offset_abs))

    cellsize: FloatProperty(
        name="Precision",
        description="Size of the cell. Smaller cells give better precision at a higher computational cost. Remember that halving the cell size means that you build a volume 8 times larger.",
        subtype="DISTANCE",
        unit="LENGTH",
        default=0.03,
        min=0.0001,
        soft_min=0.01,
    )
    offset: FloatProperty(
        name="Offset",
        description="Offset of the created surface (i.e. distance of the created surface from the original one). If offset is zero, the created surface passes on the original mesh itself. Values greater than zero mean an external surface, and lower than zero mean an internal surface. In practice this value is the threshold passed to the Marching Cube algorithm to extract the isosurface from the distance field representation.",
        subtype="DISTANCE",
        unit="LENGTH",
        default=0.0,
        soft_min=-0.1,
        soft_max=1.0,
    )
    ui_offset_abs: FloatProperty(
        name="Offset",
        description="[Absolute Mode] Offset of the created surface. Must be strictly positive. Values too close to zero may result in broken topology.",
        subtype="DISTANCE",
        unit="LENGTH",
        default=0.03,
        min=0.000001,
        soft_min=0.03,
        soft_max=1.0,
    )
    mergeclosevert: BoolProperty(
        name="Clean Vertices",
        description="If true the mesh generated by MC will be cleaned by unifying vertices that are almost coincident.",
        default=False,
    )
    discretize: BoolProperty(
        name="Discretize",
        description="If true the position of the intersected edge of the marching cube grid is not computed by linear interpolation, but it is placed in fixed middle position. As a consequence the resampled object will look severely aliased by a stairstep appearance. Useful only for simulating the output of 3D printing devices.",
        default=False,
    )
    multisample: BoolProperty(
        name="Multi-sample",
        description="If true the distance field is more accurately compute by multisampling the volume (7 sample for each voxel). Much slower but less artifacts.",
        default=False,
    )
    absdist: BoolProperty(
        name="Absolute Distance",
        description="If true a not signed distance field is computed. In this case you have to choose a not zero Offset and a double surface is built around the original surface, inside and outside. Is useful to convert thin floating surfaces into solid, thick meshes.",
        default=False,
    )


class MESHLAB_PG_generate_plane_fitting_to_selection(PropertyGroup, MeshLabFilterBase):
    pymeshlab_filter = "generate_plane_fitting_to_selection"
    requires_selection = True
    shade_flat = True
    remove_attributes = ["custom_normal", "sharp_edge", "sharp_face"]
    custom_name = "FittedPlane"

    @classmethod
    def pre_process_parameters(cls, params, props):
        # A interface do Blender usa Strings para gerenciar o Dropdown (Enum).
        # Este passo intercepta o valor e converte para Inteiro antes de enviar ao PyMeshLab.
        params["orientation"] = int(props.orientation)

        # Remove o 'selectedonly' do envio. O PyMeshLab não aceita esse argumento
        # explicitamente neste filtro específico; usamos ele apenas como gatilho interno.
        if "selectedonly" in params:
            del params["selectedonly"]

    # Variável oculta obrigatória: Força o base_filter a exportar a matriz de seleção
    # do modo de edição, mas esconde a caixa de seleção da UI, já que o filtro exige isso nativamente.
    selectedonly: BoolProperty(
        default=True,
        options={"HIDDEN"},
    )

    extent: FloatProperty(
        name="Extent (w.r.t selection)",
        description="How large is the plane, with respect to the size of the selection: 1.0 means as large as the selection, 1.1 means 10% larger then the selection.",
        default=1.0,
        min=0.001,
    )
    subdiv: IntProperty(
        name="Plane XY subdivisions",
        description="Subdivision steps of plane borders.",
        default=3,
        min=0,
    )
    hasuv: BoolProperty(
        name="UV parametrized",
        description="The created plane has an UV parametrization.",
        default=False,
    )
    orientation: bpy.props.EnumProperty(
        name="Plane orientation",
        description="Orientation of the fitting plane.",
        items=[
            (
                "0",
                "quasi-Straight Fit",
                "The fitting plane will be oriented (as much as possible) straight with the axeses.",
            ),
            (
                "1",
                "Best Fit",
                "The fitting plane will be oriented and sized trying to best fit to the selected area.",
            ),
            (
                "2",
                "XZ Parallel",
                "The fitting plane will be oriented with a side parallel with the chosen plane. WARNING: do not use if the selection is exactly parallel to a plane.",
            ),
            ("3", "YZ Parallel", "Parallel to YZ."),
            ("4", "YX Parallel", "Parallel to YX."),
        ],
        default="0",
    )
    blender_quad: BoolProperty(
        name="Quad",
        description="Convert tris to quads.",
        default=True,
    )
