import bpy
from bpy.types import PropertyGroup
from bpy.props import FloatProperty, IntProperty, BoolProperty
from ..base_filter import MeshLabFilterBase


class MESHLAB_PG_create_grid(PropertyGroup, MeshLabFilterBase):
    pymeshlab_filter = "create_grid"
    requires_selection = False
    ignore_selection_count = True
    shade_flat = True
    remove_attributes = ["custom_normal", "material_index", "sharp_edge", "sharp_face"]

    @classmethod
    def pre_process_parameters(cls, params, props):
        # Lógica Condicional RAM vs DISCO para Quad/Tri
        engine = bpy.context.scene.meshlab_prefs.processing_engine
        if engine == "DISK":
            cls.post_filter_on_true = "meshing_tri_to_quad_dominant"
            cls.post_filter_on_false = None
        else:
            cls.post_filter_on_true = None
            cls.post_filter_on_false = "meshing_poly_to_tri"

    numvertx: IntProperty(
        name="Num Vertices on X",
        description="Number of vertices on x. it must be positive.",
        default=10,
        min=2,
    )
    numverty: IntProperty(
        name="Num Vertices on Y",
        description="Number of vertices on y. it must be positive.",
        default=10,
        min=2,
    )
    absscalex: FloatProperty(
        name="X Scale",
        description="Absolute scale on x (float).",
        default=0.3,
        min=0.001,
    )
    absscaley: FloatProperty(
        name="Y Scale",
        description="Absolute scale on y (float).",
        default=0.3,
        min=0.001,
    )
    center: BoolProperty(
        name="Centered on Origin",
        description="Center grid generated by filter on origin. Grid is first generated and than moved into origin (using muparser lib to perform fast calc on every vertex).",
        default=False,
    )
    blender_quad: BoolProperty(
        name="Quad",
        description="Outputs the final mesh using quads instead of triangles.",
        default=True,
    )
