import bpy
from bpy.types import PropertyGroup
from bpy.props import FloatProperty, IntProperty, BoolProperty
from ..base_filter import MeshLabFilterBase


class MESHLAB_PG_create_grid(PropertyGroup, MeshLabFilterBase):
    pymeshlab_filter = "create_grid"
    requires_selection = False
    shade_flat = True
    remove_attributes = ["custom_normal", "material_index", "sharp_edge", "sharp_face"]

    numvertx: IntProperty(
        name="Num Vertices on X",
        description="Number of vertices on x. it must be positive.",
        default=10,
        min=2,
    )
    numverty: IntProperty(
        name="Num Vertices on Y",
        description="Number of vertices on y. it must be positive.",
        default=10,
        min=2,
    )
    absscalex: FloatProperty(
        name="X Scale",
        description="Absolute scale on x (float).",
        default=0.3,
        min=0.001,
    )
    absscaley: FloatProperty(
        name="Y Scale",
        description="Absolute scale on y (float).",
        default=0.3,
        min=0.001,
    )
    center: BoolProperty(
        name="Centered on Origin",
        description="Center grid generated by filter on origin. Grid is first generated and than moved into origin (using muparser lib to perform fast calc on every vertex).",
        default=False,
    )
